config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :favorites
    end  
  end
 
  
  resources :posts, only: [:show, :new, :create, :destroy]
  
  resources :favorites, only: [:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :tag 
  mount_uploader :img, ImgUploader
  
  has_many :favorites
  has_many :favorite_users,through: :favorites,source: :users
  
  validates :content, presence: true, length: { maximum: 400 }
  validates :sake_name, presence: true, length: { maximum: 50 }
  validates :meshi_name, presence: true, length: { maximum: 50}

  def self.search(search)
    if search
      Post.where(['content LIKE ? OR sake_name LIKE ? OR meshi_name LIKE ?', "%#{search}%","%#{search}%","%#{search}%"])
    else
      Post.all
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduce, presence: true, length: { maximum: 400 } 
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
  has_many :favorites
  has_many :favorite_posts,through: :favorites,source: :post
  
  mount_uploader :img, ImgUploader
  
  def favorite(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end
  
  def unfavorite(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  def favorite?(post)
    self.favorite_posts.include?(post)    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    current_user.favorite(post)
    flash[:success]="maru"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unfavorite(post)
    flash[:success]="batu"
    redirect_back(fallback_location: root_path)    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  
  def show
    @post = Post.find(params[:id])

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    #@post.tag_id = params[:post][:tag_id]
    #binding.pry
    if @post.save!
      flash[:success]="maru"
      redirect_to root_url
    else
      flash[:danger]="batu"
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success]="sakujo"
    head :no_content
  end

  private
  def post_params
    params.require(:post).permit(:sake_name,:meshi_name,:img,:content,:tag_id)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build  # form_with 用
      if params[:tag_id].present?
        @posts= Tag.find(params[:tag_id]).posts.search(params[:search]).order(id: :desc).page(params[:page]).per(5) 
      else
        @posts= Post.all.search(params[:search]).order(id: :desc).page(params[:page]).per(5) 
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page]).per(5)
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      flash[:success] = "seikou"
      redirect_to @user
    else
      flash[:danger] = "batu"
      render :new
    end
  end
  

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success]='変更しました'      
      redirect_to @user
    else
      flash[:danger]="失敗しました"
      render :edit
    end
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_posts.order(id: :desc).page(params[:page]).per(5)
   
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:introduce,:email,:img,:password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/favorites/_fav_btn.html.erb
<% if current_user.favorite?(post) %>
  <%= form_with(model: current_user.favorites.find_by(post_id: post.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag type: 'submit', class: "button-as_link" do %>
      <i class="fa fa-heart" style="color: pink;"></i>
    <% end %>
    <%=post.favorites.count%>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag type: 'submit', class: "button-as_link" do %>
      <i class="far fa-heart" style="color: pink;"></i>
    <% end %>
    <%=post.favorites.count%>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Microposts</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BestCombination</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/posts/_posts.html.erb
<ul class="list-unstyled mt-4">
  <% posts.each do |post| %>
    <li class="mb-4 border p-3">
      <p class="tag w-sm-25"><%=post.tag.name%></p>
      <div class="row">
        <div class="col-md-5 text-center">
          <% if post.img? %>
            <p><%= image_tag post.img.thumb.url %></p>
          <%else%>
            <p>画像なし</p>
          <% end %>          
        </div>

        <div class="col-md-7">
          <div>
            <a href="<%=post_path(post)%>" class="text-center">
              <p class="shadow-sm p-3 mb-5 bg-light rounded"><%=post.sake_name%>　×　<%=post.meshi_name%></p>
            </a>
          </div>
          <div class="mt-md-4">
            <div class="row">
              <div class="shadow-sm col-sm-8 p-2 d-flex align-items-center ml-3 mr-2">
                <% if post.user.img? %>
                  <%= image_tag post.user.img.thumb50.url,class:'rounded-circle' %>
                <%else%>
                  <%= image_tag "default.jpg", :size => '50x50' %>
                <% end %>    
                <span class="ml-3"><%= link_to post.user.name, user_path(post.user) %></span>
              </div>
              <div class="col-sm-3 text-center">
                <%if post.user == current_user%>
                  <p><i class="fa fa-heart" style="color: pink;"></i> <%=post.favorites.count%></p>
                  <p><%=link_to '削除',post_path(post),method: :delete,data: { confirm: '本当に削除してよろしいですか？' } if post.user == current_user%></p>
                <%else%>
                  <p class="d-flex align-items-end"><%=render 'favorites/fav_btn',post: post%></p>
                <%end%>              
              </div>
            </div>
          </div>
        </div>        
      </div>
    </li>
  <% end %>
  <%= paginate posts %>

</ul>

app/views/posts/new.html.erb
投稿フォーム

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :tag, 'タグ' %>
        <%= f.collection_select(:tag_id, Tag.all, :id,:name) %>
      </div>     
      
      <div class="row">
        <div class="form-group col-sm-6">
          <%= f.label :sake_name, 'お酒' %>
          <%= f.text_field :sake_name, class: 'form-control' %>
        </div>

        <div class="form-group col-sm-6">
          <%= f.label :meshi_name, '飯' %>
          <%= f.text_field :meshi_name, class: 'form-control' %>
        </div>          
      </div>
  
      
      <div class="form-group">
        <%= f.label :content, 'content' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>      
      
      <div class="form-group">
        <%= f.label :画像 %><br />
        <%= f.file_field :img, class: "img" %>        
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary btn-block mt-4' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="mx-3 border py-4 px-4">
  <p class="tag w-sm-25"><%=@post.tag.name%></p>
  <div class="row text-center">
    <div class="col-sm-5">
      <p>
        <%=@post.sake_name%>
        <%=@post.meshi_name%>        
      </p>     
    </div>      
    <div class="offset-sm-2 col-sm-5">
      <% if @post.img? %>
        <p><%= image_tag @post.img.thumb.url %></p>
      <%else%>
        <p>画像なし</p>
      <% end %>          
    </div>
  </div>
  <div class="mt-3 w-75 mx-auto bg-light px-3 py-2">
    <p class="" style="word-wrap: break-word"><%=simple_format(@post.content)%></p>
  </div>
  <div class="py-2 d-flex justify-content-between">
    <div class="shadow-sm bg-light p-2 d-flex align-items-center w-75">
      <% if @post.user.img? %>
        <%= image_tag @post.user.img.thumb50.url,class:'rounded-circle' %>
      <%else%>
        <%= image_tag "default.jpg", :size => '50x50' %>
      <% end %>    
      <span class="ml-3 "><%= link_to @post.user.name, user_path(@post.user) %> </span>
    </div>
    <div class="float-right">
      <%if @post.user == current_user%>
        <p><i class="fa fa-heart" style="color: pink;"></i> <%=@post.favorites.count%></p>
        <p><%=link_to '削除',post_path(@post),method: :delete,data: { confirm: '本当に削除してよろしいですか？' } if @post.user == current_user%></p>
      <%else%>
        <p class="d-flex align-items-end"><%=render 'favorites/fav_btn',post: @post%></p>
      <%end%>        
    </div>
  </div>
</div>

app/views/toppages/_tag_posts.html.erb
<div class="d-flex justify-content-between">
  <div>
    <%= form_tag root_url, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :name => nil %>
    <% end %>
  </div>
  <div>
    <%=link_to '投稿ページへ',new_post_path%>
  </div>
</div>

<div class="mt-5">
  <h2 class="text-center">みんなの組み合わせ</h2>
  
  <ul class="list-unstyled mt-4">
    <% posts.each do |post| %>
      <li class="mb-4 border p-3">
        <p class="tag w-sm-25"><%=post.tag.name%></p>
        <div class="row">
          <div class="col-sm-5 text-center">
            <% if post.img? %>
              <p><%= image_tag post.img.thumb.url %></p>
            <%else%>
              画像なし
            <% end %>          
          </div>
          <div class="col-sm-7">
            <div>
              <a href="<%=post_path(post)%>" class="text-center">
                <p class="shadow-sm p-3 mb-5 bg-light rounded"><%=post.sake_name%>　×　<%=post.meshi_name%></p>
              </a>
            </div>
            <div class="mt-4">
              <div class="row">
                <div class="shadow-sm bg-light col-sm-8 p-2 d-flex align-items-center">
                  <% if post.user.img? %>
                    <%= image_tag post.user.img.thumb50.url,class:'rounded-circle' %>
                  <%else%>
                    <%= image_tag "default.jpg", :size => '50x50' %>
                  <% end %>    
                  <span class="ml-3 "><%= link_to post.user.name, user_path(post.user) %> </span>
                </div>
                <div class="mx-auto pt-2">
                  <%if post.user == current_user%>
                    <i class="fa fa-heart" style="color: pink;"></i> <%=post.favorites.count%>
                    <p>
                      <%=link_to '削除',post_path(post),method: :delete, remote:true, data: { confirm: '本当に削除してよろしいですか？' },class: 'delete' if post.user == current_user%>
                    </p>
                  <%else%>
                    <p class="d-flex align-items-end"><%=render 'favorites/fav_btn',post: post%></p>
                  <%end%>              
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    <% end %>
    <%= paginate posts %>
  </ul>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="offset-sm-1 col-sm-10">
      <%= render 'tag_posts', posts: @posts %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="mt-3 mb-5">
  <p class="title shadow-sm p-3 mb-4 mt-3 bg-light rounded text-center h6"><%=user.name%><span class="ml-2">'s  ページ</span></p>
  <div class="d-flex d-row">
    <div class="col-3 text-center">
      <% if user.img? %>
        <%= image_tag user.img.thumb50.url %>
      <%else%>
        <%= image_tag "default.jpg", :size => '100x100' %>
      <% end %>
    </div>
    <div class="col-9">
      <div class="p-2 box mb-3">
        <p class="font-weight-bold">Introduce</p>
        <p class="" style="word-wrap: break-word"><%=simple_format(user.introduce)%></p>
      </div>
      <div class="mt-2 d-flex justify-content-between">
        <%if user==current_user%>
          <p><%=link_to '編集する',edit_user_path(user),class:'bbb'%></p>
        <%end%>
        <p><%=link_to 'Fav一覧',favorites_user_path(user),class:'bbb'%></p>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>Edit</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image %><br />
        <%= f.file_field :img, class: "img" %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduce, 'Introduce' %>
        <%= f.text_area :introduce, class: 'form-control' %>
      </div>      
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Edit', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<%if @favorites.present?%>
  <h3 class="text-center"><%=@user.name%>のお気に入りの組み合わせ</h3>
  <%=render 'posts/posts', posts: @favorites%>
<%else%>
  <h3 class="text-center"><%=@user.name%>のお気に入りはまだありません</h3>
<%end%>

app/views/users/index.html.erb
<% if @users.any? %>
  <ul class="list-unstyled">
    <% @users.each do |user| %>
      <li class="border row col-sm-8 ml-auto mr-auto mt-3">
        <div class="col-sm-2 ml-auto mr-auto mt-2">
          <% if user.img? %>
            <%= image_tag user.img.thumb50.url %>
          <%else%>
            <%= image_tag "default.jpg", :size => '50x50' %>
          <% end %>          
        </div>

        <div class="col-sm-8 ml-sm-2">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'プロフィールへ', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  <div class="mt-4">
    <%= paginate @users %>
  </div>
  </ul>
  
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image %><br />
        <%= f.file_field :img, class: "img" %>
      </div>

      <div class="form-group">
        <%= f.label :introduce, 'Introduce' %>
        <%= f.text_area :introduce, class: 'form-control' %>
      </div>      
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="offset-sm-1 col-sm-10">
    <%=render 'user',user: @user%>
    
    <%=@user.name%>の投稿
    <ul class="list-unstyled mt-4">
      <% @posts.each do |post| %>
        <li class="mb-4 border p-3">
          <p class="tag w-sm-25"><%=post.tag.name%></p>
          <div class="row">
            <div class="col-md-5 text-center">
              <% if post.img? %>
                <p><%= image_tag post.img.thumb.url %></p>
              <%else%>
                <p>画像なし</p>
              <% end %>          
            </div>
    
            <div class="col-md-7">
              <div>
                <a href="<%=post_path(post)%>" class="text-center">
                  <p class="shadow-sm p-3 mb-5 bg-light rounded"><%=post.sake_name%>　×　<%=post.meshi_name%></p>
                </a>
              </div>
              <div class="mt-md-4">
                <div class="row">
                  <div class="col-sm-3 text-center">
                    <%if post.user == current_user%>
                      <p><i class="fa fa-heart" style="color: pink;"></i> <%=post.favorites.count%></p>
                      <p><%=link_to '削除',post_path(post),method: :delete,data: { confirm: '本当に削除してよろしいですか？' } if post.user == current_user%></p>
                    <%else%>
                      <p class="d-flex align-items-end"><%=render 'favorites/fav_btn',post: post%></p>
                    <%end%>              
                  </div>
                </div>
              </div>
            </div>        
          </div>
        </li>
      <% end %>
      <%= paginate @posts %>
    </ul> 
  </div>
</div>